name: Dismiss Dependabot alerts
author: Austen Stone
description: dismiss Dependabot alerts via the GraphQL API
branding:
  icon: "x-circle"
  color: "purple"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false
  dismiss-reason:
    description: The reason for dismissing the review. 'FIX_STARTED' | 'INACCURATE' | 'NO_BANDWIDTH' | 'NOT_USED' | 'TOLERABLE_RISK'
    default: "NOT_USED"
    required: false
  scope:
    description: The scope. "DEVELOPMENT" | "RUNTIME"
    default: "DEVELOPMENT"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
